### ISSUE TITLE
There's A BUG

### ISSUE THREAD

**Issue by VanshCodes** [crhenr/youtube-video-maker#5]
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "yvm.py", line 52, in <module>
    img = image_robot.get_image(keywords, search_term)
  File "/home/devarea/MEGA/MEGAsync Uploads/MyProFiles/Python/youtube-video-maker/src/imagerobot.py", line 20, in get_image
    return self.response.download(arguments)[keywords][0]
TypeError: tuple indices must be integers or slices, not str

**Comment by irrational-Pi** [comment]
I got the same issue. Did you found any solutions?

**Comment by irrational-Pi** [comment]
return self.response.download(arguments)[0][keywords]

**Comment by cristianzsh** [comment]
Fixed [#90509b8](https://github.com/crhenr/youtube-video-maker/commit/90509b8738228e15b8680c40a23802790d4f8347).

Thank you.
